name: Swift

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphoneos --show-sdk-path`" -Xswiftc "-target" -Xswiftc "arm64-apple-ios14.0"
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          swift package generate-xcodeproj
          xcodebuild build -sdk iphoneos -scheme 'DebugMenu-Package'
          xcodebuild test -destination 'name=iPhone 11' -scheme 'DebugMenu-Package'
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install 
        run: |
          git clone https://github.com/unsignedapps/swift-create-xcframework.git
          cd swift-create-xcframework
          make install
      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v1.4.0